# Copyright (c) 2016-2020 Knuth Project developers.
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+$/
  - dev

env:
   global:
     - CONAN_REFERENCE: "lmdb/0.9.22"
     - CONAN_USERNAME: "kth"
     - CONAN_LOGIN_USERNAME: "fpelliccioni"
     - CONAN_CHANNEL: "stable"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/k-nuth/kth"
    #  - CONAN_STABLE_BRANCH_PATTERN: "release/*"

linux: &linux
   os: linux
   sudo: required
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker

osx: &osx
   os: osx
   language: generic

matrix:
   include:

      # Linux, GCC, libstdc++ ------------------------------------------------------
      - <<: *linux
        env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9

      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8

      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7

      # - <<: *linux
      #   env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=conanio/gcc6

      # - <<: *linux
      #   env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=conanio/gcc5

      # - <<: *linux
      #   env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=conanio/gcc49

      # Linux, Clang, libstdc++ ----------------------------------------------------
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/clang9

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/clang8

      # - <<: *linux
      #   env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang7

      # - <<: *linux
      #   env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=conanio/clang60

      # - <<: *linux
      #   env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=conanio/clang50

      # - <<: *linux
      #   env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=conanio/clang40

      # - <<: *linux
      #   env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=conanio/clang39
        

      # macOS, apple-Clang, libc++ -------------------------------------------------

      - <<: *osx
        osx_image: xcode11
        env: CONAN_APPLE_CLANG_VERSIONS=11.0

      - <<: *osx
        osx_image: xcode10.3
        env: CONAN_APPLE_CLANG_VERSIONS=10.0

      # - <<: *osx
      #   osx_image: xcode9.4
      #   env: CONAN_APPLE_CLANG_VERSIONS=9.1

      # - <<: *osx
      #   osx_image: xcode9.3
      #   env: CONAN_APPLE_CLANG_VERSIONS=9.1

      # - <<: *osx
      #   osx_image: xcode9
      #   env: CONAN_APPLE_CLANG_VERSIONS=9.0

      # - <<: *osx
      #   osx_image: xcode8.3
      #   env: CONAN_APPLE_CLANG_VERSIONS=8.1

      # # - <<: *osx
      # #   osx_image: xcode7.3
      # #   env: CONAN_APPLE_CLANG_VERSIONS=7.3
      
install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  #- export CONAN_PRINT_RUN_COMMANDS=TRUE
  #- export CONAN_LOGGING_LEVEL=10
  - chmod +x .travis/run.sh
  - ./.travis/run.sh

